class ErrorCodes:
    # 400 – Bad Request
    INVALID_REQUEST = "INVALID_REQUEST"
    INVALID_PARAMETERS = "INVALID_PARAMETERS"
    MISSING_PARAMETERS = "MISSING_PARAMETERS"
    INVALID_STATUS = "INVALID_STATUS"
    INVALID_AMOUNT = "INVALID_AMOUNT"
    INVALID_TRANSACTION_TYPE = "INVALID_TRANSACTION_TYPE"
    COUNTRY_NOT_SUPPORTED = "COUNTRY_NOT_SUPPORTED"
    CURRENCY_NOT_ALLOWED = "CURRENCY_NOT_ALLOWED"

    # 401 – Unauthorized
    INVALID_CREDENTIALS = "INVALID_CREDENTIALS"
    EXPIRED_CREDENTIALS = "EXPIRED_CREDENTIALS"
    INVALID_TOKEN = "INVALID_TOKEN"
    UNKNOWN_IP_ADDRESS = "UNKNOWN_IP_ADDRESS"

    # 403 – Forbidden
    AUTHORIZATION_REQUIRED = "AUTHORIZATION_REQUIRED"

    # 404 – Not Found
    PAYMENT_NOT_FOUND = "PAYMENT_NOT_FOUND"
    CUSTOMER_NOT_FOUND = "CUSTOMER_NOT_FOUND"
    TRANSACTION_NOT_FOUND = "TRANSACTION_NOT_FOUND"
    REPORT_NOT_FOUND = "REPORT_NOT_FOUND"

    # 405 – Method Not Allowed
    UNSUPPORTED_METHOD = "UNSUPPORTED_METHOD"

    # 409 – Conflict
    IDEMPOTENCY_DUPLICATED = "IDEMPOTENCY_DUPLICATED"

    # 500 / 504 – Server
    INTERNAL_ERROR = "INTERNAL_ERROR"
    REQUEST_TIMEOUT = "REQUEST_TIMEOUT"
